
- name: "Setup pre-requisite for k8s cluster"
  hosts: cluster
  become: true
  gather_facts: true

  vars:
    K8S_VERSION: "1.29"
    INSTALL_KUBE_BINARIES: true
    PACKAGES:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  tasks:
    - name: "Ensure kernel modules configuration file exists"
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: '0644'

    - name: "Load kernel modules"
      modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: "Ensure sysctl config for Kubernetes exists"
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1
        owner: root
        group: root
        mode: '0644'

    - name: "Reload sysctl settings"
      command: sysctl --system

    - name: "Update apt cache and install prereq packages"
      apt:
        name: "{{ PACKAGES }}"
        state: present
        update_cache: yes

    - name: "Remove kubernetes apt source if present"
      file:
        path: /etc/apt/sources.list.d/kubernetes.list
        state: absent

    - name: "Ensure /etc/apt/keyrings exists"
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
        owner: root
        group: root

    - name: "Add Docker GPG key (Debian/Ubuntu)"
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: "Add Docker APT repository (Debian/Ubuntu)"
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Install Docker CE and containerd (Debian/Ubuntu)"
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: "Ensure Docker service is running and enabled"
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true
      when: ansible_os_family == "Debian"

    - name: "Add vagrant user to docker group"
      user:
        name: vagrant
        groups: docker
        append: yes
      ignore_errors: yes

    - name: "Install additional packages required for containerd (Debian/Ubuntu)"
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
      when: ansible_os_family == "Debian"

    - name: "Ensure Docker GPG key (alternative) is present"
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
      when: ansible_os_family == "Debian"

    - name: "Ensure containerd package installed"
      ansible.builtin.apt:
        name: containerd.io
        state: present
      when: ansible_os_family == "Debian"

    - name: "Generate default containerd config if missing"
      ansible.builtin.command: containerd config default > /etc/containerd/config.toml
      args:
        creates: /etc/containerd/config.toml

    - name: "Reload systemd daemon"
      command: systemctl daemon-reload

    - name: "Restart and enable containerd service"
      service:
        name: containerd
        state: restarted
        enabled: yes

    - name: "Remove swapfile entries from /etc/fstab (if any)"
      mount:
        name: swap
        fstype: swap
        state: absent
      ignore_errors: yes

    - name: "Disable swap at runtime if active"
      command: swapoff -a
      when: ansible_swaptotal_mb is defined and ansible_swaptotal_mb > 0

    - name: "Delete kubernetes keyrings if exists"
      file:
        path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        state: absent

    - name: "Check if containerd config exists in /vagrant"
      stat:
        path: /vagrant/config/containerd/config.toml
      register: containerd_config

    - name: "Copy containerd config from /vagrant if present"
      copy:
        src: /vagrant/config/containerd/config.toml
        dest: /etc/containerd/config.toml
      when: containerd_config.stat.exists

    - name: "Configure Node IP for kubelet"
      lineinfile:
        path: /etc/default/kubelet
        line: 'KUBELET_EXTRA_ARGS=--node-ip={{ (ansible_eth1.ipv4.address | default(omit)) if (ansible_eth1 is defined and ansible_eth1.ipv4 is defined) else (ansible_default_ipv4.address) }}'
        create: yes

    - name: "Check if /usr/bin/kubelet exists"
      stat:
        path: /usr/bin/kubelet
      register: kubelet_bin
      ignore_errors: yes

    - name: "Restart kubelet service (only if kubelet installed)"
      service:
        name: kubelet
        state: restarted
        daemon_reload: yes
        enabled: yes
      when: kubelet_bin.stat.exists

    - name: "Ensure kubectl (and optional kubeadm/kubelet) binaries are present (fallback)"
      become: true
      shell: |
        set -euo pipefail
        STABLE=$(curl -L -s https://dl.k8s.io/release/stable.txt)
        # kubectl
        if [ ! -x /usr/local/bin/kubectl ]; then
          echo "Downloading kubectl ${STABLE} to /usr/local/bin/kubectl"
          curl -L -o /usr/local/bin/kubectl https://dl.k8s.io/release/${STABLE}/bin/linux/amd64/kubectl
          chmod +x /usr/local/bin/kubectl
        else
          echo "/usr/local/bin/kubectl already exists"
        fi

        # optional kubeadm & kubelet static binaries (do not register services)
        if [ "{{ INSTALL_KUBE_BINARIES | bool }}" = "True" ] || [ "{{ INSTALL_KUBE_BINARIES | bool }}" = "true" ]; then
          if [ ! -x /usr/local/bin/kubeadm ]; then
            echo "Downloading kubeadm ${STABLE} to /usr/local/bin/kubeadm"
            curl -L -o /usr/local/bin/kubeadm https://dl.k8s.io/release/${STABLE}/bin/linux/amd64/kubeadm
            chmod +x /usr/local/bin/kubeadm
          else
            echo "/usr/local/bin/kubeadm already exists"
          fi

          if [ ! -x /usr/local/bin/kubelet ]; then
            echo "Downloading kubelet ${STABLE} to /usr/local/bin/kubelet"
            curl -L -o /usr/local/bin/kubelet https://dl.k8s.io/release/${STABLE}/bin/linux/amd64/kubelet
            chmod +x /usr/local/bin/kubelet
          else
            echo "/usr/local/bin/kubelet already exists"
          fi
        fi
      args:
        executable: /bin/bash

    - name: "Ensure /usr/bin symlink for kubectl"
      file:
        src: /usr/local/bin/kubectl
        dest: /usr/bin/kubectl
        state: link

    - name: "Stat kubeadm binary"
      stat:
        path: /usr/local/bin/kubeadm
      register: stat_kubeadm

    - name: "Ensure /usr/bin symlink for kubeadm if installed"
      file:
        src: /usr/local/bin/kubeadm
        dest: /usr/bin/kubeadm
        state: link
      when: INSTALL_KUBE_BINARIES | bool and stat_kubeadm.stat.exists

    - name: "Stat kubelet binary"
      stat:
        path: /usr/local/bin/kubelet
      register: stat_kubelet

    - name: "Ensure /usr/bin symlink for kubelet if installed"
      file:
        src: /usr/local/bin/kubelet
        dest: /usr/bin/kubelet
        state: link
      when: INSTALL_KUBE_BINARIES | bool and stat_kubelet.stat.exists

    - name: "Add vagrant user to docker group (best-effort)"
      user:
        name: vagrant
        groups: docker
        append: yes
      ignore_errors: yes
