
- name: "Setup pre-requisite for k8s cluster"

  hosts: cluster
  become: true
  become_method: sudo
  gather_facts: true

  vars:
    K8S_VERSION: "1.29"
    INSTALL_KUBE_BINARIES: true

  tasks:

  - name: "Setting up Configuration for IP Bridge"
    shell: |
      cat << EOF | sudo tee /etc/modules-load.d/k8s.conf
      overlay
      br_netfilter
      EOF

      sudo modprobe overlay
      sudo modprobe br_netfilter

      cat << EOF | sudo tee /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
      EOF

      sudo sysctl --system

  - name: "Install pre-requisite packages"
    apt:
      name: "{{ PACKAGES }}"
      state: present
      update_cache: yes

    vars:
      PACKAGES:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

  - name: "Remove kubernetes apt source if present"
    file:
      path: /etc/apt/sources.list.d/kubernetes.list
      state: absent

  - name: "Add an apt signing key for container package"
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: "Install containerd service and dependencies"
    apt:
      name: "{{ PACKAGES }}"
      state: present
      update_cache: yes

    vars:
      PACKAGES:
        - docker-ce
        - docker-ce-cli
        - containerd.io


  - name: "Reload systemd daemon"
    command: systemctl daemon-reload

  - name: "Enable and Start containerd service"
    service:
      name: containerd
      state: restarted
      enabled: yes

  - name: "Remove swapfile from '/etc/fstab'"
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent

    with_items:
      - swap
      - none

  - name: "Disable Swap"
    command: sudo swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: "Ensure apt keyrings directory exists"
    file:
      path: /etc/apt/keyrings
      state: directory

  - name: "Delete kubernetes keyrings if exists"
    file:
      path: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      state: absent

  - name: "Check if containerd config exists in /vagrant"
    stat:
      path: /vagrant/config/containerd/config.toml
    register: containerd_config

  - name: "containerd configuration setup (only if config present)"
    copy:
      src: /vagrant/config/containerd/config.toml
      dest: /etc/containerd/config.toml
    when: containerd_config.stat.exists

  - name: "Configure Node IP"
    lineinfile:
      path: /etc/default/kubelet
      line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_eth1.ipv4.address }}
      create: yes

  - name: "Check if kubelet binary exists"
    stat:
      path: /usr/bin/kubelet
    register: kubelet_bin
    ignore_errors: yes

  - name: "Restart kubelet service (only if kubelet installed)"
    service:
      name: kubelet
      state: restarted
      daemon_reload: yes
      enabled: yes
    when: kubelet_bin.stat.exists

  - name: "Ensure kubectl (and optionally kubeadm/kubelet) binaries are present (fallback)"
    become: true
    shell: |
      set -euo pipefail
      STABLE=$(curl -L -s https://dl.k8s.io/release/stable.txt)
      # kubectl
      if [ ! -x /usr/local/bin/kubectl ]; then
        echo "Downloading kubectl ${STABLE} to /usr/local/bin/kubectl"
        curl -L -o /usr/local/bin/kubectl https://dl.k8s.io/release/${STABLE}/bin/linux/amd64/kubectl
        chmod +x /usr/local/bin/kubectl
      else
        echo "/usr/local/bin/kubectl already exists"
      fi

      # optional kubeadm & kubelet static binaries (do not register services)
      if [ "{{ INSTALL_KUBE_BINARIES }}" = true ]; then
        if [ ! -x /usr/local/bin/kubeadm ]; then
          echo "Downloading kubeadm ${STABLE} to /usr/local/bin/kubeadm"
          curl -L -o /usr/local/bin/kubeadm https://dl.k8s.io/release/${STABLE}/bin/linux/amd64/kubeadm
          chmod +x /usr/local/bin/kubeadm
        else
          echo "/usr/local/bin/kubeadm already exists"
        fi

        if [ ! -x /usr/local/bin/kubelet ]; then
          echo "Downloading kubelet ${STABLE} to /usr/local/bin/kubelet"
          curl -L -o /usr/local/bin/kubelet https://dl.k8s.io/release/${STABLE}/bin/linux/amd64/kubelet
          chmod +x /usr/local/bin/kubelet
        else
          echo "/usr/local/bin/kubelet already exists"
        fi
      fi
    args:
      executable: /bin/bash

  - name: "Ensure /usr/bin symlinks for kubectl (and optional kubeadm/kubelet)"
    file:
      src: /usr/local/bin/kubectl
      dest: /usr/bin/kubectl
      state: link

  - name: "Ensure /usr/bin symlink for kubeadm if installed"
    stat:
      path: /usr/local/bin/kubeadm
    register: kubeadm_bin

  - name: "Ensure /usr/bin symlink for kubeadm if installed"
    file:
      src: /usr/local/bin/kubeadm
      dest: /usr/bin/kubeadm
      state: link
    when: INSTALL_KUBE_BINARIES | bool and kubeadm_bin.stat.exists

  - name: "Ensure /usr/bin symlink for kubelet if installed"
    stat:
      path: /usr/local/bin/kubelet
    register: kubelet_bin

  - name: "Ensure /usr/bin symlink for kubelet if installed"
    file:
      src: /usr/local/bin/kubelet
      dest: /usr/bin/kubelet
      state: link
    when: INSTALL_KUBE_BINARIES | bool and kubelet_bin.stat.exists

  - name: "Add vagrant user to docker group"
    user:
      name: vagrant
      groups: docker
      append: yes
